media:
  input: content/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    filename: "{primary}.mdx"
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: docs
    label: Visum Docs
    type: collection
    path: 'content/docs'
    filename: "{primary}.mdx"
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
