media:
- name: Images
  label: Images
  input: content/media
  output: /src/cms/content/media
- name: Files
  label: files
  input: content/files
  output: /src/cms/content/files
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    filename: '{primary}.mdx'
    view:
      fields: [ title, categories, published, allow_comment, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
      - name: author
        label: Author
        type: reference
        options:
          label: "{aname}"
          value: "{slug}"
          collection: authors
      - name: slug
        label: Slug
        type: string
      - name: title
        label: Title
        type: string
      - name: categories
        label: Categories
        type: reference
        options:
          label: "{title}"
          value: "{slug}"
          collection: categories
      - name: cover
        label: Cover Image
        type: image
      - name: allow_comment
        label: Allow Comments
        type: boolean
      - name: thread_id
        label: Comment Thread ID
        type: number
      - name: excerpt
        label: Excerpt
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: sharing
        label: Sharing
        type: object
        fields:
          - name: og_image
            label: Open Graph Image
            type: image
            description: URL to image for Open Graph sharing
          - name: twitter_image
            label: Twitter Image
            type: image
            description: URL to image displayed in the Twitter card (min 120x120px)
          - name: twitter_card
            label: Twitter Card Type
            type: select
            options:
              values:
              - label: Summary
                value: summary
              - label: Summary with Large Image
                value: summary_large_image
              - label: App
                value: app
              - label: Player
                value: player
          - name: twitter_site
            label: Twitter Site Username
            type: string
            description: The @username for the website (e.g. @norskiThailand)
          - name: twitter_creator
            label: Content Creator Username
            type: string
            description: The @username of the content creator
          
  - name: docs
    label: Visum Docs
    type: collection
    path: 'content/docs'
    filename: '{primary}.mdx'
    view:
      fields: [ title, slug, published, date ]
    fields:
      - name: slug
        label: Slug
        type: string
      - name: published
        label: Published
        type: boolean
        default: true
      - name: updated
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
      - name: title
        label: Title
        type: string
      - name: excerpt
        label: Excerpt
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: sharing
        label: Sharing
        type: object
        fields:
          - name: og_image
            label: Open Graph Image
            type: image
            description: URL to image for Open Graph sharing
          - name: twitter_image
            label: Twitter Image
            type: image
            description: URL to image displayed in the Twitter card (min 120x120px)
      - name: prev
        label: Previous
        type: boolean
        default: false
      - name: next
        label: Next
        type: boolean
        default: false


  - name: guides
    label: Guides
    type: collection
    path: 'content/guides'
    filename: '{primary}.mdx'
    view:
      fields: [ title, slug, published, date ]
    fields:
      - name: slug
        label: Slug
        type: string
      - name: published
        label: Published
        type: boolean
        default: true
      - name: updated
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
      - name: title
        label: Title
        type: string
      - name: excerpt
        label: Excerpt
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: sharing
        label: Sharing
        type: object
        fields:
          - name: og_image
            label: Open Graph Image
            type: image
            description: URL to image for Open Graph sharing
          - name: twitter_image
            label: Twitter Image
            type: image
            description: URL to image displayed in the Twitter card (min 120x120px)
      - name: prev
        label: Previous
        type: boolean
        default: false
      - name: next
        label: Next
        type: boolean
        default: false





  - name: categories
    label: Categories
    type:  collection
    path: 'content/_data/categories'
    filename: '{primary}.json'
    format: json
    fields:
      - name: title
        label: Title
        required: true
        type: string
      - name: slug
        label: Slug
        required: true
        type: string
      - name: description
        label: Description
        type: string
      - name: color
        label: Color
        type: string

  - name: authors
    label: Authors
    type:  collection
    path: 'content/_data/authors'
    filename: '{primary}.json'
    format: json
    fields:
      - name: aname
        label: Name
        required: true
        type: string
      - name: slug
        label: Slug
        required: true
        type: string
      - name: bio
        label: Bio
        type: string
      - name: link
        label: Link
        type: string
      - name: profile_photo
        label: Profile Photo
        type: image